### ISSUE TITLE
log the full link of the localhost

### ISSUE THREAD

**Issue by Abbbyccc** [fac26/week2-database-ggkl#24]
<img width="561" alt="Screenshot 2023-01-25 at 17 10 43" src="https://user-images.githubusercontent.com/88027905/214632784-0c179c26-1e74-42b0-af55-d3eb17186f18.png">

probably can try to log the localhost link like this? -->> **_console.log(`Listening at http://localhost:${PORT}`)_**
make it easier to link directly from the terminal

**Comment by georgiaewhitney** [comment]
Thanks, Abby! All fixed!
