### ISSUE TITLE
Code style recommendation

### ISSUE THREAD

**Issue by ko-karol** [fac26/week2-database-ggkl#29]
https://github.com/fac26/week2-database-ggkl/blob/b39a56478ff8aec93857eb88de6a1ff29bc6b22e/model/genres.js#L1-L11

I would consider putting module.exports at the bottom of the file so it's clearer that you're exporting after everything else. The only time this would really matter is if you used arrow functions instead of regular functions.

**Comment by georgiaewhitney** [comment]
Thank you, @Kr33L - great shout. We have implemented this throughout the code.
