### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by lisahns** [fac26/week2-database-ggkl#31]
I'd recommed this in your index.js file

![image](https://user-images.githubusercontent.com/92580887/214639582-0e104e2a-9b86-4a24-b279-f1756179096c.png)

it'll create a clickable link on your terminal to visit localhost, instead of having to type it in your browser. You don't have to do that but I think it makes life a little easier :)

**Comment by georgiaewhitney** [comment]
Added this -thank you, Lisa!
